---
- name: 創建 {{BIN_DIR}} 目錄
  file:
    dest={{ BIN_DIR }} 
    state=directory mode=0740

- name: 複製 ETCD 二進制文件
  copy:
    src={{ETCD_DIR}}/{{item}} 
    dest={{BIN_DIR}}/{{item}} 
    mode=0540
  with_items:
  - etcd
  - etcdctl

- name: 創建ETCD工作目錄 /var/lib/etcd
  file: 
    path=/var/lib/etcd 
    state=directory

- name: 生成 etcd.service 服務配置
  template: 
    src=etcd.service.j2 
    dest=/etc/systemd/system/etcd.service

- name: 重新加載 systemd
  command: systemctl daemon-reload

- name: 啟動 etcd
  service:
    name=etcd
    state=restarted
    enabled=yes
