---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web01
  labels:
    name: nginx-web01
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-web01
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-web01
  labels:
    app: nginx-web01
spec:
  replicas: 3
  strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-web01
    spec:
      containers:
        - name: nginx-web01
          image: k8s.ipebg.com/library/nginx:v0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            readinessProbe:
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: 2
              memory: 512Mi
            limits:
              cpu: 4
              memory: 1024Mi
          ports:
            - name: http
              containerPort: 80 
