# 安裝kube-node
# ---
- name: 下載kubeadm-{{KUBE_VERSION}} images文件
  get_url:
    url=http://192.168.1.88/kubeadm-images-{{KUBE_VERSION}}.tar.gz
    dest=/tmp/kubeadm-images-{{KUBE_VERSION}}.tar.gz

- name: 導入kubeadm-{{KUBE_VERSION}} images文件
  shell: '{{BIN_DIR}}/docker load -i /tmp/kubeadm-images-{{KUBE_VERSION}}.tar.gz'

- name: 獲取加入集群 token命令
  shell: 'kubeadm token create --print-join-command'
  register: k8s_token
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 複製加入集群執行脚本
  template: src=cluster.join.sh.j2 dest=/tmp/cluster.join.sh mode=0755

- name: 加入現有集群
  shell: "sh /tmp/cluster.join.sh"
